### ISSUE TITLE
Link to an example maybe?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [FransBouma/DocNet#2]

**Comment by FransBouma** [comment]
Yeah that's a good idea :) The thing was: when I uploaded the stuff I had to update the site I was using it for. I have now: http://www.llblgen.com/documentation/5.0/designer/index.htm

I linked to it on my blog, but indeed it should be in the readme as well! Will add that tomorrow.

**Comment by FransBouma** [comment]
Implemented http://fransbouma.github.io/DocNet/
