### ISSUE TITLE
Samples directory?

### ISSUE THREAD

**Issue by cmbrown1598** [FransBouma/DocNet#20]
Looking through the code provided, there's no real documentation (HA!) about what the JSON files and directory contents should be / look like.  Can you take the source you created http://fransbouma.github.io/DocNet/index.htm from, and put it in a Sample directory?

**Comment by FransBouma** [comment]
First, it's on the documentation site: http://fransbouma.github.io/DocNet/docnetjson.htm

Second, it's in the repository, as stated, but in the gh-pages branch: https://github.com/FransBouma/DocNet/tree/gh-pages

**Comment by FransBouma** [comment]
If it's the markdown source you're looking for, it's in the 'MarkdownSource' subfolder: https://github.com/FransBouma/DocNet/tree/gh-pages/MarkdownSource
