### ISSUE TITLE
Maybe support Redcarpet extensions?

### ISSUE THREAD

**Issue by chadbr** [FransBouma/DocNet#21]
GitHub uses the Redcarpet renderer for .md content...

https://george-hawkins.github.io/basic-gfm-jekyll/redcarpet-extensions.html

?

Thanks, Chad

**Comment by FransBouma** [comment]
Most of them are already available, if you need specific extensions, please open an issue about that. Not sure if they're implemented though, except perhaps superscript/subscript, for which there is already an issue open (#8)
