### ISSUE TITLE
Docnet 0.14.0 fails in Win7

### ISSUE THREAD

**Issue by myicq** [FransBouma/DocNet#42]
The latest version 0.14.0 fails in Windows 7.

Latest version 0.13.x works as expected.

Problem with **NavigationLevel.cs**

Debug output:
`d:\apps\DOCNET>docnet  d:\apps\DOCNET\DOCNET_HELP\DocNet-gh-pages\MarkdownSource
Docnet v0.14.0. (c)2016 Frans Bouma
Get your copy at: https://github.com/FransBouma/Docnet

Copying theme 'L2NoSearch'
Copying source folders to copy.
Generating pages in 'd:\apps\DOCNET\DOCNET_HELP\DocNet-gh-pages'
Exception: System.IO.DirectoryNotFoundException
Description: En del af stien 'd:\apps\DOCNET\DOCNET_HELP\DocNet\src\DocNet\NavigationLevel.cs' blev ikke fundet.
Stack-trace:
   ved System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   ved System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileSha
re share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boole
an useLongPath, Boolean checkHost)
   ved System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, File
Options options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   ved System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 buff
erSize, Boolean checkHost)
   ved System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   ved System.IO.File.ReadAllText(String path, Encoding encoding)
   ved Projbook.Extension.DefaultSnippetExtractor.LoadFile(String fullFilename)
   ved Projbook.Extension.CSharpExtractor.CSharpSnippetExtractor.Extract(String fullFilename, String memberPattern)
   ved MarkdownDeep.BlockProcessor.HandleSnippetExtension(Block b)
   ved MarkdownDeep.BlockProcessor.HandleDocNetExtension(Block b)
   ved MarkdownDeep.BlockProcessor.EvaluateLine(Block b)
   ved MarkdownDeep.BlockProcessor.EvaluateLine()
   ved MarkdownDeep.BlockProcessor.ScanLines()
   ved MarkdownDeep.Markdown.ProcessBlocks(String str)
   ved MarkdownDeep.Markdown.Transform(String str, Dictionary`2& definitions)
   ved Docnet.Utils.ConvertMarkdownToHtml(String toConvert, String destinationDocumentPath, String siteRoot, String sour
ceDocumentFilename, List`1 createdAnchorCollector)
   ved Docnet.SimpleNavigationElement.GenerateOutput(Config activeConfig, NavigatedPath activePath)
   ved Docnet.NavigationLevel.GenerateOutput(Config activeConfig, NavigatedPath activePath)
   ved Docnet.NavigationLevel.GenerateOutput(Config activeConfig, NavigatedPath activePath)
   ved Docnet.NavigationLevel.GenerateOutput(Config activeConfig, NavigatedPath activePath)
   ved Docnet.Engine.GeneratePages()
   ved Docnet.Engine.DoWork()
   ved Docnet.Program.Main(String[] args)
Inner exception:
<null>

d:\apps\DOCNET>docnet

`

**Comment by FransBouma** [comment]
Please provide a repro case as it's related to your theme.

**Comment by myicq** [comment]
Frans, I am not sure exactly what you mean. 
I took the standard Windows installer for version 0.14.0, and tried to recreate the help files. Get the error above. 

So everything is unmodified as per the installer.

I assume no reason to send you same files / structure as is in the installer ?

**Comment by FransBouma** [comment]
You mean, you used the default .zip file and pulled the markdown files from the docs of DocNet? What's odd is this: `Copying theme 'L2NoSearch'` in the stacktrace. There's no such theme. That's why I am a bit puzzled what's going on. :)

**Comment by myicq** [comment]
True, I did change the default template, but the change is only in the HTML part. (remove the search box, since I don't need it). Should not modify generation.

Did another test with everything as supplied: the docnet-gh-pages  source, default template. Same result: failure in NavigationLevel

Description: Could not find a part of the path 'c:\APPS\docnet\DocNet\src\DocNet\NavigationLevel.cs'.

The stack trace output is the same.

**Comment by FransBouma** [comment]
Hmm. I can't reproduce it with the docs source folder and 0.14 (which we use extensively to produce our massive documentation sets). It might be there's a file missing in the zip file or something. I'll see if I can reproduce it on another VM.

**Comment by FransBouma** [comment]
I couldn't reproduce it on the box where the source is, but could reproduce it on a box which didn't contain the source. Couldn't figure it out till I saw what the file was which was missing: navigationlevel.cs. This is a snippet reference from the direct source file. In this page: http://fransbouma.github.io/DocNet/markdownextensions.htm#snippets

There, it refers to a piece of code from DocNet to show the feature. It refers to the actual sourcefile and therefore it has to be present (as that's how the snippets feature works: it refers to real files so you don't have to copy things). When the source isn't available or elsewhere, the snippet reference of that page fails and you'll get that error (which is also why it refers to a .cs file).

So it works fine, the docs of docnet itself require that the source is close to it (see the md file for the path), so the snippets feature works :)
