### ISSUE TITLE
Home (__index) not auto-generating ToC

### ISSUE THREAD

**Issue by GeertvanHorrik** [FransBouma/DocNet#49]
It looks like the Home item does not auto-create the ToC based on the headers. Is that by purpose or a bug?

**Comment by FransBouma** [comment]
This is on purpose, as the __index page is shown when you click a section header in the ToC: it then will show the pages in the section and there's then actually no page active. I admit it's not very consistent, as the headers on the __index page could create a subsection in the ToC like when you click a page. However it's rather awkward to have this section in the ToC as there's no page it is then placed below: the page it belongs to is the section header... So I picked the least awkward one, which is no ToC section there. 

In general, you could opt for no __index page. It will then be generated for you, and add a page with what the section is all about as the first page in the section

**Comment by GeertvanHorrik** [comment]
Thanks, that might be just what I was looking for. It looks like it generates `Home.htm` and no longer an index.htm (thus page will not load by default). Will just add a dummy redirect as index.htm as a workaround.
