### ISSUE TITLE
Support automatic linking

### ISSUE THREAD

**Issue by GeertvanHorrik** [FransBouma/DocNet#50]
I am currently converting a large documentation site from Confluence to docnet. So far so good, but I noticed (it's also documented) that links to local md files don't get transformed.

Interested in a PR?

If so, links will be converted if:

1. They are listed in docnet.json (so have a generated htm page)
2. Are relative

**Comment by GeertvanHorrik** [comment]
Btw this could be optional via the docnet.json.

**Comment by FransBouma** [comment]
sounds good :) Indeed, with an option (default off) in docnet.json so to get this you need to enable it. This does require a change to the markdown parser, so the PR should come with a few test cases. The test cases are straightforward: you provide a .txt and a .htm file, the txt file is the input, the htm file the output it should give, see the Docnet test folder in the markdowndeep folder https://github.com/FransBouma/DocNet/tree/master/src/MarkdownDeepTests/testfiles/docnetmode

As it's a DocNet specific option, the markdowndeep parser should check if the DocNet mode is enabled, if not, it shouldn't execute the option (so not autolink md to htm). I have to check if '.htm' or '.html' is also configurable...

**Comment by GeertvanHorrik** [comment]
On it!

**Comment by GeertvanHorrik** [comment]
btw I see you are using Assert.AreEqual for the tests. You might want to look into ApprovalTests to compare files (but that's out of scope for this ticket).

**Comment by FransBouma** [comment]
The tests were already there when I forked the markdowndeep repo ;) so I just kept the system and added the files. This works fine tho, so I kept it

**Comment by GeertvanHorrik** [comment]
I see you don't actually store the config on the Markdown class (not required so far). Can I introduce a new property on Markdown, same as on the Config class?

**Comment by FransBouma** [comment]
Yes, you can place it below DocNetMode on the MarkdownDeep class (near the bottom). A simple bool will suffice. Most features added to MarkdownDeep for DocNet are controlled by DocNetMode as they're simply extensions to the markdown but this is a change in how links are handled, and to avoid breaking things it should be optional if DocNetMode is enabled. I know it's a bit odd to keep MarkDownDeep clean as here it's used solely for DocNet but it's now re-usable if one wants to use it somewhere else (which I have, in HnD vNext) so it's better to add a separate property to MarkdownDeep.cs

The parsing is a bit getting used to. You have to follow the calls a bit to understand what it is doing and where things are converted. There are several string utilities available, and be aware of not scanning beyond the end of the file ;). Links also can contain '#' characters and a relative id, so you need to scan for '.md' or '.MD'.
