### ISSUE TITLE
Where to store the attachments

### ISSUE THREAD

**Issue by GeertvanHorrik** [FransBouma/DocNet#51]
Just a question someone might have already solved. Where do you store the attachments?

1. In a separate includes/attachments folder (nested or flat)
2. Next to the md src files

**Comment by FransBouma** [comment]
what do you mean exactly with 'attachments' ? :)

**Comment by GeertvanHorrik** [comment]
Images, zip files with examples, etc

**Comment by FransBouma** [comment]
Ah! In a separate folder. See: "SourceFoldersToCopy" in the docnet.json file. The folders specified (see docnet.json doc http://fransbouma.github.io/DocNet/docnetjson.htm) are relative to source.

**Comment by GeertvanHorrik** [comment]
I found that, but it looks kind of weird to separate images from md files, but guess it's just getting used to.

**Comment by FransBouma** [comment]
ah I see what you mean. If you look at an md file and the support files for it (images) as a unit it indeed looks weird, but the idea in docnet is that the files combined form a unit, the site. Therefore having images in a separated folder, dedicated for that, makes sense, after all it's common practice to do it that way for a normal website too.

**Comment by GeertvanHorrik** [comment]
Thanks, makes sense.
