### ISSUE TITLE
Add more replacement variables for the templates

### ISSUE THREAD

**Issue by GeertvanHorrik** [FransBouma/DocNet#53]
I am trying to create a footer like this:

```
<p>Is this section not up-to-date or found an issue? Please <a href="https://github.com/Catel/catel.github.io/src/{{RelativeFileName}}" target="_blank">contribute</a>!</p>
```

Therefore I think we could introduce a few new variables:

1. FileName (full path to the file being processed)
2. RelativeFileName (relative (to the docnet.json file) file path of the file being processed)

What do you think? Happy to PR.

**Comment by FransBouma** [comment]
Sounds good!

**Comment by GeertvanHorrik** [comment]
I know it's a bit dirty, but can I just push to the same PR? I already have it working on the doc site:

https://catel.github.io/vnext/tips-tricks/mvvm/finding-view-of-view-model.htm

**Comment by FransBouma** [comment]
I'd rather like you push a different PR, sorry :) I'll look into them shortly (later today)
