### ISSUE TITLE
Generate sitemap

### ISSUE THREAD

**Issue by GeertvanHorrik** [FransBouma/DocNet#55]
To create improved search capabilities, I think it would help to generate a sitemap?

Let me know if you are interested, then I can try to create a PR.

**Comment by FransBouma** [comment]
would that be equal to an expanded ToC?

**Comment by GeertvanHorrik** [comment]
Yes, sort of, but it's for SEO

https://en.wikipedia.org/wiki/Sitemaps

**Comment by FransBouma** [comment]
Reading that it doesn't tell me how sitemaps add something the pages currently not already provide: the sitemap, an xml file it seems, can contain extra info about the pages, but what extra info are you going to provide in the sitemap.xml file?

All pages are reachable through the tocs on the pages, so the crawler of a search engine can reach and index all pages already, and while crawling can find the relationship between the pages. Not sure how a sitemap can add to this, could you elaborate a bit in what way a sitemap can be beneficial?

**Comment by GeertvanHorrik** [comment]
You are right, the crawler will probably go through all of this via the ToC anyway. Sitemaps are probably good for dynamic content, but since we are generating static (always linked via the ToC) content, this might be overkill.

The only benefit would be the "last updated" timestamp, but that's it.

**Comment by FransBouma** [comment]
yeah thought about that too, however 'last updated' is the same for all files, all files are generated in 1 go all the time, so that should be read from the file date of the source file... it's also to be seen whether these files are still used by search engines. E.g. what Google uses is unknown.

**Comment by GeertvanHorrik** [comment]
Ok, then let's close this issue, thanks for the discussion.
