### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by GeertvanHorrik** [FransBouma/DocNet#56]
While debugging my solution to #48 , I accidentally found out that some images were missing / could not be resolved. I think this can be improved by adding colored logging.

**Comment by FransBouma** [comment]
that will be difficult I think, as the parser doesn't know of any files. Checks have to be done after the fact, which results in a broken links check over the site...

**Comment by GeertvanHorrik** [comment]
But at least we can *warn* people that something went wrong in the process. Now I just found out because I had first-chance exceptions enabled and had a debugger attached.

**Comment by FransBouma** [comment]
ok, but how would you do that?  :) An exception? The tool doesn't have a tracer and writing things to stdout will very likely go unnoticed.

**Comment by GeertvanHorrik** [comment]
Right, makes sense. And adding a log file will making merging future updates a pain. Let's close this one.
