### ISSUE TITLE
Support heading 3 items in the side-ToC (as option?)

### ISSUE THREAD

**Issue by GeertvanHorrik** [FransBouma/DocNet#59]
See for example this page:

http://docs.catelproject.com/vnext/reference/Catel.Core/Catel/Argument.htm

Would be *extremely* useful to have a list of properties / methods on the left side as well. I can create a PR if you are interested.

**Comment by FransBouma** [comment]
The page you link to shows a ToC that's showing only the H2? H3's as well as H2's... I've tried that initially but it didn't look great.

**Comment by GeertvanHorrik** [comment]
The thing is that H1 is not supported in the ToC as well. So we can only have top-levels as docs. But then it would only show Properties, Methods, etc. If I make these H1, then it just looks like big pile of members.

As an additional option (off by default)?

**Comment by FransBouma** [comment]
H1 is the page title, so the type you're generating the docs for. H2's are then the sections in the page, like properties, methods. I see your point of adding H3's for this particular case, but I really have to see the HTML and layout. As I said, I tried to add it (as a bigger ToC helps discoverability) but never got a layout which really looked OK, it was always a mess.

**Comment by GeertvanHorrik** [comment]
Let me introduce the option in a fork and you can always decide whether you want to support this or not.

**Comment by GeertvanHorrik** [comment]
I am currently making the following changes:

1. Instead of tracking just h2, track all h elements in a list
2. Create a hierarchy at the end (covered with unit tests)
3. Add a MaxToCLevel (defaults to 2)

This way we can easily extend the behavior (e.g. I can pass in 3, and it should auto generate 3 levels, etc)

**Comment by FransBouma** [comment]
Ok, but with what HTML? :) Say I have 4 levels, how will that look like?

**Comment by GeertvanHorrik** [comment]
That's up to the one that wants to include 4 levels ;-)

I am just adding the technical possibility to deal with multiple levels of headings (instead of just h2). Once that is done, we can simple see how it deals with these levels.

**Comment by FransBouma** [comment]
Ok. Building the hierarchy can be tricky though, as well as keeping track if which element belongs to what: there can be an H2 and an H4, but no H3 between them. I think it can be done without the need of building a hierarchy at the end, as the file is parsed from top to bottom, so you know what the current 'top' / previous element level is.

**Comment by GeertvanHorrik** [comment]
I have unit tests for that scenario :)

**Comment by GeertvanHorrik** [comment]
![image](https://user-images.githubusercontent.com/1246444/27129413-773d7ae4-5102-11e7-8e9f-6b7569f90995.png)

**Comment by FransBouma** [comment]
Cool! :)

> I have unit tests for that scenario :)

Famous Last Words (tm) ;)
