### ISSUE TITLE
Generate 404 page

### ISSUE THREAD

**Issue by GeertvanHorrik** [FransBouma/DocNet#62]
Sometimes you get a 404 page. It would be nice if we could generate a 404 page (including ToC).

**Comment by GeertvanHorrik** [comment]
At first I thought I could get passed this by forcing a 404.md, but then it gets added to the ToC. I think we an support a 404.md in the root which will automatically be generated as well.

**Comment by FransBouma** [comment]
Ok, tho 404's are only supported by a webserver. Docs are also meant to be read off-line. 
A dedicated option in the docnet.json file with a reference to the 404.md might work though. All that's needed is generate a 404.htm in the root, the machinery is there, it's indeed not to be added to the ToC, which might need some extra code. 

Another option is to simply use a boolean flag in the docnet.json: 'generate 404 page', which will emit a htm file with the toc like with any other file, but with predefined content (like the generated index pages): "404 Page not found".  

The 404.md option is more flexible tho.

**Comment by GeertvanHorrik** [comment]
Once the other PR is accepted, I will go for the option you've described (default true I assume)?

**Comment by GeertvanHorrik** [comment]
![image](https://user-images.githubusercontent.com/1246444/27828545-f65879e0-60bc-11e7-92ca-2efd950cbe22.png)
