### ISSUE TITLE
Typo in filename

### ISSUE THREAD

**Issue by GeertvanHorrik** [FransBouma/DocNet#67]
![image](https://user-images.githubusercontent.com/1246444/27560592-10fd076e-5ac5-11e7-8bfd-b8b54c834019.png)

Not sure if worth fixing, but wanted to let you know.

**Comment by FransBouma** [comment]
Hmm... that looks rather silly indeed. I've recently renamed a folder where case changed and git saw it as 2 separate folders which was a bit of a pain, so renaming this needs a bit of git-voodoo to get this properly added again I think. 

I forked this from MarkdownDeep, wonder if they have it badly named as well. Not a high priority, but something to do after your other PR is merged :)

**Comment by GeertvanHorrik** [comment]
Changing case is hard in git (I use 2 commits for that), a rename is not, so this shouldn't be a problem. Will fix after you have merged the other one.

**Comment by FransBouma** [comment]
Will now release v0.16. :)

**Comment by GeertvanHorrik** [comment]
I have 2 more features :)

**Comment by FransBouma** [comment]
then I'll wait and won't stand in your way! :D
