### ISSUE TITLE
Proposal: NuGet package for msbuild integration

### ISSUE THREAD

**Issue by craigktreasure** [FransBouma/DocNet#79]
I took some time in a [fork](https://github.com/craigktreasure/DocNet/commits/craig/NuGet) to create a simple tool NuGet package that integrates the DocNet commands into msbuild. This allows you to easily integrate DocNet into a project's build process. Is there any interest in taking a look at a pull request? I'd be happy to write up some documentation as well.

**Comment by FransBouma** [comment]
Ok, so this nuget package contains the .exe and alters the csproj of the project if added, where is the .exe going to get its config file from if I may ask? :) That's a bit unclear. It's primarily designed to run on a set of md files in a folder structure, not part of a code base (as the doc files are separated from the code).

**Comment by craigktreasure** [comment]
The NuGet package contains the DocNet tooling as well as targets and props files that will alter the build of the csproj, yes. The targets file (see [here](https://github.com/craigktreasure/DocNet/blob/craig/NuGet/src/DocNet/nuget/build/Docnet.targets)) is simply a wrapper around the DocNet CLI.

There are a couple of configuration options available.

By default, the configuration is assumed to be in the project directory, but you can configure its location by setting DocnetJsonPath in your csproj. For example:
``` XML
<DocnetJsonPath>$(MSBuildProjectDirectory)..\myDocNetConfigPath\</DocnetJsonPath>
```

To clear the destination folder, you can set DocnetClearDestinationFolder to true in your csproj.
``` XML
<DocnetClearDestinationFolder>true</DocnetClearDestinationFolder>
```

My scenario is pretty simple. I have an ASP.NET Core 2.0 website that hosts the DocNet output. My Markdown content also happens to be part of that project with my DocNet configuration in the project directory and configured to output the content in my web root (wwwroot) directory. This simplifies building and publishing the documentation.

While I don't expect this to fit everyone's use cases and needs (you've obviously got plenty of users who are happy without it), it does provide a very simple way to include the DocNet content generation into the msbuild build process.

I hope that makes more sense and am open to suggestions. You know your users better than I do. This made our process much simpler and I thought it could be helpful to others as well.

**Comment by FransBouma** [comment]
Ah I see :) Well, to be honest, I have no idea what most of the users do (as in how they build the docs, with which tooling) :) I do know what we do and that's run it through cmd scripts which are started from msbuild. What I wonder is though: what about using the `Exec` msbuild task? we use that in msbuild to e.g. run a command or batch script and it could run docnet easily: https://msdn.microsoft.com/en-us/library/x8zx72cd.aspx did you try that or wasn't it sufficient?

**Comment by craigktreasure** [comment]
If you take a look at the [targets](https://github.com/craigktreasure/DocNet/blob/craig/NuGet/src/DocNet/nuget/build/Docnet.targets) file that comes with the NuGet package, that's exactly what it does. It runs DocNet.exe using the `Exec` task. The NuGet package is nice because it does a few things for you:
1. You can obtain DocNet from the NuGet package, so you don't need to check a version of DocNet into your source or write extra scripts to pull it in. **This was a big one for me.**
2. It hooks up the execution of DocNet into msbuild for you. Users no longer need to be instructed to use the `Exec` task themselves as it's already been written for them.
3. DocNet can still be run independently when using the NuGet package by running `msbuild my.csproj /target:RunDocnet` or `dotnet msbuild /target:RunDocnet` (it actually makes a VS Code task quite handy).
3. Updating to a newer version of DocNet can be as easy as updating any other NuGet package.

**Comment by FransBouma** [comment]
Ok, though it distributes DocNet through a nuget package, something I don't want (as I am against distributing tools through nuget, as I believe nuget shouldn't be used for distributing executables). So I don't know what to do here, as I don't want to ignore your effort in creating something which uses my code, but I also don't want docnet being distributed through nuget...

**Comment by craigktreasure** [comment]
I'm curious what your preferred method for distributing executables is. I think it's nice that there are options.

A few years ago, i would have agreed with you on NuGet packages; however, NuGet got a lot of support for tools packages with the release of Visual Studio 2017. If you don't agree with the changes they've made, then that's one thing, but there is support and precedent for tools packages and they are pretty common in the new .NET Core world. I think NuGet as a tool for distribution of build components is a good thing and is even more cemented as such through the newer ‘dotnet’ infrastructure.

I hope you don't feel like I'm pressuring you here. I'm just trying to have a meaningful discussion. There are different philosophies and I understand that not everyone agrees at times. And that's OK! At the end of the day, it's your project and you need to be able to support (in more way that one) whatever contributions you take.

**Comment by FransBouma** [comment]
:) 

The main thing I have against distributing stuff other than simple dll's through nuget is that it often requires installationscripts and pollutes the meaning of the dependency system. Installation scripts are IMHO a potential security risk and I think nuget should forbid them altogether. This then results in simple packages with dlls/assemblies you take a dependency on in your project without hassle/installation scripts or other code that has to run to make the thing that's distributed useful. If there's a requirement for a tool/plugin site then they should create that besides nuget. 

I agree it's not a PoV that's been shared by all, and that's fine :) I just think my own stuff should at least do what I think is best and that's not being up there as a package. I'm sorry, but I can't merge your contribution that way.

**Comment by craigktreasure** [comment]
@FransBouma I realize you've closed this, but i want to make this clear. The NuGet package I created does not have any installation scripts and if anything it reinforces the dependency system. This is a package, just like any other, that your project may depend upon to statically compile documentation. It doesn't pollute your project and is removed as easily as it is added. It doesn't require customers to write their own scripts to download, extract, and store a tool somewhere and then require a different build step to produce the documentation. Those were requirements from my team.

I understand your decision and it doesn't sound like we're going to see eye to eye on this, so I'll keep my fork active since my team does find it useful.

**Comment by FransBouma** [comment]
@craigktreasure Oh that's perfectly fine, I didn't want to imply anything else :) I closed it as I didn't want to proceed with the package on nuget. :) As I think docnet is pretty stable (as in: I don't see much change on the horizon) I think keeping your own fork is not going to take a lot of effort.
