### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by Stoffe** [FransBouma/DocNet#82]
Some good features to add to DocNet.

1: Export to pdf feature
It is very common that one would need to export a version of the documentation automatically to pdf format...
(This would also need to include version nr of the documentation)

(Please note the need to links inside the pdf too, and pictures to be embedded...)

2: Automatically translate
Use one of the online services to automatically translate the content to another language.

**Comment by FransBouma** [comment]
Converting to PDF is a nightmare, it requires printing to a PDF converter printer and this in general gives terrible quality when you convert from a webpage. So this will not be added. 

Automatically translate... dunno, most automatic translators are pretty terrible in general if you want to convert a whole page.

**Comment by Stoffe** [comment]
Really??
Since converting to pdf is one of the most common functions that companies require to be able to verify a specific version at a specific point I am very surprised to hear this comment.

**Comment by FransBouma** [comment]
what they require is noted, but really, converting webpages to pdf is very complex. Try it for once :) We did it for years with our chm files (which are basically html files and a ToC) and it was terrible. To convert to pdf, you need to print the page to a pdf converting printer. Good luck with that :)
