### ISSUE TITLE
When pressing Enter in search field on search page it directs to 404 page

### ISSUE THREAD

**Issue by chocmake** [FransBouma/DocNet#92]
When on the search page (`Docnet_search.htm`) if one presses Enter within the search box it directs to a 404 page.

Noticed on the Framed site but figured it affects this project. Might be something to do with title case vs lowercase difference? As the 404 has a lowercase `docnet_search.htm` in the URL.

[Example search query](https://framedsc.com/Docnet_search.htm?q=test)

Visual demo:
![Demo](https://github.com/FransBouma/DocNet/assets/34178938/42874cfd-69a9-4411-a679-48d051c75a98)

**Comment by FransBouma** [comment]
Yeah I think it's to do with the casing. In the docs page of my software (where I have written docnet for initially): https://www.llblgen.com/Documentation/5.10/LLBLGen%20Pro%20RTF/index.htm which runs on windows, no casing issues occur when I hit enter in the search box.

**Comment by FransBouma** [comment]
If you rename the docnet_search.htm to Docnet_search.htm in the URL on the 404, it works. So it's a casing issue. I think we can correct that in the template on the framed site (as it's hosted on github which does filter files on casing. why they do that is beyond me (yes it's a linux thing, but usability wise it's stupid)

**Comment by chocmake** [comment]
> In the docs page of my software (where I have written docnet for initially): https://www.llblgen.com/Documentation/5.10/LLBLGen%20Pro%20RTF/index.htm which runs on windows, no casing issues occur when I hit enter in the search box.

Ah so it's some Github specific thing, good to know. I notice it also affects the [fransbouma.github.io](http://fransbouma.github.io/DocNet/) docs.

**Comment by FransBouma** [comment]
Indeed, as these are also running on github. Websites running on windows inherit the case insensitivity of the filesystem they're hosted on, and on unix/linux it's the same thing basically. I think it's an easy fix in the template files we're using in the framed site. Will try to fix it today :)
